set ruler
set number

" install pathogen
call pathogen#infect()

" tell vim to keep a backup file
set backup
" tell vim where to put its backup files
set backupdir=$HOME/.vim/tmp
" " tell vim where to put swap files
set dir=$HOME/.vim/tmp

" Map esc to `jk`
inoremap jk <esc>

" Incremental search
set incsearch

highlight ExtraWhitespace ctermbg=red guibg=red
" The following alternative may be less obtrusive.
highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
" " Try the following if your GUI uses a dark background.
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
