set nocompatible  " We don't want vi compatibility.

set ruler  " line and column numbers
set number " line numbers (on the left)

" install pathogen
call pathogen#infect()

" tell vim to keep a backup file
set backup
" tell vim where to put its backup files
set backupdir=$HOME/.vim/tmp
" " tell vim where to put swap files
set dir=$HOME/.vim/tmp

" Map esc to `jk`
inoremap jk <esc>

" Incremental search
set incsearch

" Highlight trailing characters
match ErrorMsg '\s\+$'

let g:ack_default_options = " -H --nocolor --nogroup --column"

"colorscheme
set background=dark
let g:solarized_termcolors=128
let g:solarized_termtrans=1
colorscheme solarized

"map leader to `,`
let mapleader = ","

map <Leader>N :NERDTree<cr>
